### ISSUE TITLE
Contribution, licensing

### ISSUE THREAD

**Issue by cgarrovillo** [christianselig/Amplosion#1]
Since this is an open-source paid app, how are contributions & thus licensing approached? :)

**Comment by christianselig** [comment]
You're welcome to send a pull request, but I can't promise anything if it's not inline with what I'm hoping to do with the app obviously. 

To be honest my interest with open sourcing was to have transparency in what the code is doing for anyone curious, not as a means for others to build similar products with my code. I hope that's understandable.

**Comment by falconmick** [comment]
Yeah fair enough, after googling it’s really hard to find a standard licence for “open source but not yours to do build my completion with” maybe there is but all the licenses I’ve read all feel too permissive for what you want

**Comment by christianselig** [comment]
Right? That's exactly what I was thinking.

**Comment by cgarrovillo** [comment]
Do let me know if any of you have found a license that is restrictive but still open-source. 

Otherwise, really what's stopping anyone from ripping this code and making their own Amplosion

**Comment by TechnologyClassroom** [comment]
Currently, the project is copyright and source available until a license is added.

Since GPL licenses are incompatible with the Apple App store, I would recommend MIT or Apache-2.0.  This would make the app free software and open source.

**Comment by christianselig** [comment]
@TechnologyClassroom Not licensing a project doesn't make it a free for all to steal. As GitHub lists, not listing a license means:

> meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work

**Comment by falconmick** [comment]
Yeah it’s probably the right call, maybe a readme update explaining the no
licence choice is the way to go

**Comment by christianselig** [comment]
Done!

**Comment by TechnologyClassroom** [comment]
No license is copyright and proprietary.

The reddit post today said open source which this is not.

**Comment by falconmick** [comment]
*opens source* I think there is perhaps a confusion here open source is so often combined with permissive licensing, however that doesn't mean open source is open usage.

**Comment by TechnologyClassroom** [comment]
The Open Source Initiative does not recognize no license as an open source license.  Proprietary code that can only be viewed is referred to as source available.  Source available only includes one piece of freedom 1 of the four essential freedoms.

Calling Amplosion open source is false advertising.

**Comment by christianselig** [comment]
Respectfully, I think this fits the colloquial definition of open source that your average person (myself included) views as open source and would recognize, and I'm more than happy with that.
